### ISSUE TITLE
Use the minus sign

### ISSUE THREAD

**Issue by michaeljota** [focusaurus/express_code_structure#8]
>The JavaScript language is camelCase (toString, toLowerCase, etc), and this: "-" is a minus sign. I don't know why people do var myModule = require("my-module");. It's just silly. Don't put minus signs in filesystem paths or package names.

Camelcase are not allowed anymore

```shell
forbidden New packages must have all-lowercase names
```

The minus sign it's now being used instead.

**Comment by focusaurus** [comment]
@michaeljota Thanks for this suggestion. Although I think that rule is silly/terrible, I don't think it matters enough to bikeshed it, so I have updated this repo to v3.0.0 with lower-kebab-case filenames.
